### ISSUE TITLE
renaming the repository

### ISSUE THREAD

**Issue by mkuzak** [esciencecenter-digital-skills/model-coupling-workshop#11]
Thank you so much for your work on this lesson 🥇 
To align with our training infrastructure, it would help if you rename the repository to `lesson-model-coupling`.
All our lessons start with `lesson-`. Also, in our terminology workshop is an event, an activity of teaching based on the lesson.

**Comment by raar1** [comment]
No problem @mkuzak , I've changed the name and updated the links now.
